apiVersion: cloud-build-notifiers/v1
kind: SlackNotifier
metadata:
  name: slack-notification
spec:
  notification:
    filter: build.status in [Build.Status.PENDING, Build.Status.SUCCESS, Build.Status.QUEUED, Build.Status.FAILURE, Build.Status.TIMEOUT, Build.Status.CANCELLED, Build.Status.INTERNAL_ERROR]
    params:
      buildStatus: $(build.status)
    delivery:
      webhookUrl:
        secretRef: webhook-url
    template:
      type: golang
      uri: gs://$BUCKET_NAME/slack.json
  secrets:
    - name: webhook-url
    # value: projects/example-project/secrets/example-slack-notifier-webhook-url/versions/latest
      value: projects/$PROJECT_NUMBER/secrets/slack-secret/versions/2